
 /* 비트 연산 활용 */
SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE
GENOTYPE & 2 = 0 AND
(GENOTYPE & 4 = 4 OR GENOTYPE & 1 = 1)

 /* 바닐라 */
SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE
BIN(GENOTYPE) = 1  OR
BIN(GENOTYPE) = 01 OR
(
LENGTH(BIN(GENOTYPE)) >= 3 AND
SUBSTRING(BIN(GENOTYPE), LENGTH(BIN(GENOTYPE)) -1, 1) != 1 AND
(SUBSTRING(BIN(GENOTYPE), LENGTH(BIN(GENOTYPE)) -2, 1) = 1 OR SUBSTRING(BIN(GENOTYPE), LENGTH(BIN(GENOTYPE)), 1) = 1 )
)